name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hacs-validation:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
